version: '3.9'
services:
    sonarqube:
        image: 'sonarqube:latest'
        container_name: 'sonar-qube'
        depends_on:
            - sonar_db
            - smart-budget
            - finance-administration
            - finance-db
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: sonar
        ports:
            - "9000:9000"
        volumes:
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
            - sonarqube_temp:/opt/sonarqube/temp
    sonar_db:
        image: 'postgres:14.11'
        container_name: 'sonar-db'
        environment:
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
            POSTGRES_DB: sonar
        volumes:
            - sonar_db:/var/lib/postgresql
            - sonar_db_data:/var/lib/postgresql/data
    smart-budget:
        image: 'nyos777/smart-budget'
        container_name: 'smart-budget'
        ports:
            - '8081:8081'
        restart:
            always
        depends_on:
            - finance-db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://finance-db/financeDB
            - SPRING_DATASOURCE_USERNAME=finance
            - SPRING_DATASOURCE_PASSWORD=finance
    finance-administration:
        image: 'nyos777/finance-administration'
        container_name: 'administration'
        ports:
            - '8080:8080'
        restart:
            always
        depends_on:
            - finance-db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://finance-db/financeDB
            - SPRING_DATASOURCE_USERNAME=finance
            - SPRING_DATASOURCE_PASSWORD=finance
    finance-db:
        image: 'postgres:14.11'
        container_name: 'financeDB'
        ports:
            - '5437:5432'
        environment:
            - POSTGRES_USER=finance
            - POSTGRES_PASSWORD=finance
            - POSTGRES_DB=financeDB
        restart: always
        volumes:
            - finance_data:/var/lib/postgresql/data
volumes:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    sonarqube_temp:
    sonar_db:
    sonar_db_data:
    finance_data: